sudo: required
services: 
  - docker

before_install:
  - docker build -t tatianamerjan/docker-react -f Dockerfile.dev .

script:
  - docker run tatianamerjan/docker-react npm run test -- --coverage